accounts/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup, name='signup'), 
    path('login/',views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<str:username>/', views.profile, name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('photos/', include('photos.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'photos'

urlpatterns = [
    path('',views.index, name='index'),    # READ - Index
    #path('new/',views.new, name='new'),     # CREATE - 폼 전달
    path('create/',views.create, name='create'),   # CREATE - DB 저장
    path('<int:photo_pk>/',views.detail, name='detail'),     # READ - Detail
    path('<int:photo_pk>/delete/', views.delete, name='delete'),     # delete
    path('<int:photo_pk>/update/', views.update, name='update'),     # UPDATE - DB 저장
    path('<int:photo_pk>/comment/', views.comment_create, name='comment_create'), # 댓글 생성
    path('<int:photo_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'), # 댓글 삭제
    path('<int:photo_pk>/like/', views.like, name='like'),
    path('<int:photo_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
    path('list/', views.list, name='list'),
    path('explore/', views.explore, name='explore'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
    path('test/', views.test, name='test'),
]

photos/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
  content = models.TextField(unique=True)

  def __str__(self):
    return self.content

class Photo(models.Model):
  photo = models.ImageField()
  content = models.TextField()
  longitude = models.FloatField()
  latitude = models.FloatField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
  hashtags = models.ManyToManyField(Hashtag, blank=True)
  
  def __str__(self):
    return f'[{self.pk}] {self.photo}'

class Comment(models.Model):
  photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  content = models.TextField(max_length=300)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  class Meta:
    ordering = ['-pk',]

  def __str__(self):
    return self.content  

photos/forms.py
from django import forms
from .models import Photo, Comment

class PhotoForm(forms.ModelForm) :
  photo = forms.FileInput(
  )
  
  
  
  # 메타 데이터 -> 데이터의 데이터
  # ex) 사진 한장 (촬영장비 이름, 촬영환경 등)
  class Meta:
    model = Photo
    fields = ('photo','content')


class CommentForm(forms.ModelForm):
  content = forms.CharField(
    label='댓글',
    widget=forms.Textarea(
      attrs={
        'class':'content',
        'placeholder':'댓글 입력해라...',
        'rows':1,
        
      }
    )
  )

  class Meta:
    model = Comment
    fields = ('content',)

photos/views.py
import hashlib
from itertools import chain
from IPython import embed
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Photo, Comment, Hashtag
from .forms import PhotoForm, CommentForm

# Create your views here.
def index(request):
  # if request.user.is_authenticated:
  #   gravatar_url = hashlib.md5(request.user.email.encode('utf-8').lower().strip()).hexdigest()
  # else:
  #   gravatar_url = None

  photos = Photo.objects.all()
  context = {'photos':photos,}
  return render(request,'photos/index.html',context)

@login_required
def create(request):
  #사용자로부터 데이터를 받아서 DB에 저장하는 함수
  if request.method == 'POST':
    form = PhotoForm(request.POST, request.FILES)
    # embed()
    if form.is_valid():
      photo = form.save(commit = False)

      photo.longitude = 0.456
      photo.latitude = 0.111
      
      photo.user = request.user

      photo=form.save()
      # hashtag
      # 게시글 내용을 split해서 리스트로 만듦
      for word in photo.content.split():
        # word가 '#'으로 시작할 경우 해시태그 등록
        if word.startswith('#'):
          hashtag, created = Hashtag.objects.get_or_create(content=word)
          photo.hashtags.add(hashtag)
    return redirect('photos:detail', photo.pk)
  else:
    form = PhotoForm()

  #form으로 전달받는 형태 2가지
  # 1. GET 요청 -> 비어있는 폼 전달
  # 2. 유효성 검증 실패 -> 에러 메시지를 포함한 채로 폼 전달
  context = {'form':form}
  return render(request,'photos/form.html', context)

#게시글 상세정보를 가져오는 함수
def detail(request,photo_pk):
  #article = Article.objects.get(pk=article_pk)
  photo = get_object_or_404(Photo, pk=photo_pk)
  
  person = get_object_or_404(get_user_model(), pk=photo.user_id)
  comment_form = CommentForm()
  comments = photo.comment_set.all()
  context = {
    'photo':photo,
    'person':person,
    'comment_form':comment_form,
    'comments':comments,
  }
  return render(request,'photos/detail.html',context)

@require_POST
def delete(request, photo_pk):
  # 지금 사용자가 로그인 되어 있는가?
  if request.user.is_authenticated:
    # 삭제할 게시글 가져옴  
    photo = get_object_or_404(Photo, pk=photo_pk)
    # 지금 로그인한 사용자와 게시글 작성자 비교
    if request.user == photo.user:
      photo.delete()
    else:
      return redirect('photos:detail', photo.pk)
  return redirect('photos:index')
  
@login_required
def update(request, photo_pk):
  photo = get_object_or_404(Photo, pk=photo_pk)
  if request.user == photo.user:
    if request.method == 'POST':
      form = PhotoForm(request.POST, instance=photo)
      if form.is_valid():
        photo = form.save()
        # hashtag
        photo.hashtags.clear()
        for word in photo.content.split():
          if word.startswith('#'):
            hashtag, create = Hashtag.objects.get_or_create(content=word)
            photo.hashtags.add(hashtag)

        return redirect('photos:detail', photo.pk)
    else :
      form = PhotoForm(instance=photo)
  else:
    return redirect('photos:index')

  context = {
    'form':form,
    'photo':photo,
  }
  return render(request, 'photos/form.html', context)

# 댓글 생성 뷰 함수
@require_POST
def comment_create(request, photo_pk):
  if request.user.is_authenticated:
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
      comment = comment_form.save(commit=False)
      comment.user = request.user
      comment.photo_id = photo_pk
      comment.save()
  return redirect('photos:detail', photo_pk)


#댓글 삭제 뷰 함수
@require_POST
def comment_delete(request, photo_pk, comment_pk):
  # 1. 로그인 여부 확인
  if request.user.is_authenticated:
    comment = get_object_or_404(Comment, pk=comment_pk)
    # 2. 로그인한 사용자와 댓글 작성자가 같을 경우
    if request.user == comment.user:
      comment.delete()
  return redirect('photos:detail', photo_pk)

@login_required
def like(request, photo_pk):
  # 좋아요 누를 게시글 가져오기
  photo = get_object_or_404(Photo, pk=photo_pk)
  # 현재 접속하고 있는 유저
  user = request.user

  # 현재 게시글을 좋아요 누른 사람 목록에서, 
  # 현재 접속한 유저가 있을 경우 -> 좋아요 취소
  if user in photo.like_users.all():
    photo.like_users.remove(user)
  # 목록에 없을 경우 -> 좋아요 누르기
  else:
    photo.like_users.add(user)
  return redirect('photos:index')

@login_required
def follow(request, photo_pk, user_pk):
  # 게시글 작성한 유저
  person = get_object_or_404(get_user_model(), pk=user_pk)
  # 지금 접속하고 있는 유저
  user = request.user
  # 게시글 작성 유저 팔로워 명단에 접속 중인 유저가 있을 경우
  # -> 언팔
  if person != user :
    if user in person.followers.all():
      person.followers.remove(user)
    # 명단에 없으면
    # -> 팔로우
    else:
      person.followers.add(user)
    # 게시글 상세정보로 redirect
  return redirect('photos:detail', photo_pk)

# 내가 팔로우 하는 사람의 글 + 내가 작성한 글
def list(request):
  # 내가 팔로우하고 있는 사람들
  followings = request.user.followers.all()
  # 내가 팔로우하고 있는 사람들 + 나 -> 합치기
  followings = chain(followings, [request.user])
  # 위 명단 사람들 게시글 가져오기
  photos = Photo.objects.filter(user__in=followings).order_by('-pk').all()
  comment_form = CommentForm()
  context = {
    'photos':photos,
    'comment_form':comment_form,
  }
  return render(request, 'photos/photo_list.html', context)

# 모든 사람 글
def explore(request):
  photos = Photo.objects.all()
  comment_form = CommentForm()
  context = {
    'photos':photos,
    'comment_form':comment_form,
  }
  return render(request, 'photos/photo_list.html', context)

def hashtag(request, hash_pk):
  # 해시태그 가져오기
  hashtag = get_object_or_404(Hashtag, pk=hash_pk)
  # 해당 해시태그를 참조하는 게시글들 가져오기
  photos = hashtag.photo_set.order_by('-pk')
  context = {
    'hashtag' : hashtag,
    'photos' : photos,
  }
  return render(request, 'photos/hashtag.html', context)



def test(request):
  return render(request, 'photos/test.html')

config/templates/photos/_follow.html
<div class="jumbotron">
  <h1 class="display-4">{{ person.username }}</h1>
  <p class="lead">
    팔로워: {{ person.followers.all|length }}명 | 
    팔로앙: {{ person.followings.all|length }}명
  </p>
  <h3>팔로워 다 나와라</h3>
  {% for follower in person.followers.all %}
    {{ follower.username }}
  {% empty %}
    <p>팔로워가 없어요...</p>
  {% endfor %}
  <hr class="my-4">
  {% if user != photo.user %}
  <a class="btn btn-primary btn-lg" href="{% url 'photos:follow' photo.pk person.pk %}" role="button">
    {% if user in person.followers.all %}
      unfollow
    {% else %}
      follow
    {% endif %}
  </a>
  {% endif %}
</div>

config/templates/photos/_nav.html
{% load gravatar %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'photos:index' %}">
    <h2>
      <p>TriPhoto</p>
      {% comment %} <img src = "https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?s=80&d=mp" alt =""> {% endcomment %}
      {% comment %} Hello, {{ user.username }} {% endcomment %}
    </h2>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        {% comment %} <li>
          <a class="nav-link" href="{% url 'photos:list' %}">좋은글 보기</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'photos:explore' %}">전부 보기</a>
        </li> {% endcomment %}

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'photos:create' %}">사진 올리기</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:profile' user.username %}">Mypage</a>
        {% comment %} </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:update' %}">정보수정</a>
        </li> {% endcomment %}
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:change_password' %}">암호변경</a>
        </li> {% endcomment %}
        {% comment %} <form action="{% url 'accounts:delete' %}" method="POST" style="display: inline;">
          {% csrf_token %}
          <input type="submit" value="회원탈퇴" class="btn btn-danger">
        </form> {% endcomment %}
      {% else %}
        <li>
          <a href="{% url 'accounts:login'%}">로그인</a>
        </li>
        <li>
          <a href="{% url 'accounts:signup'%}">회원가입</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

config/templates/photos/_photo.html
  <figure class="snip1368">
    <img data-toggle="modal" data-target="#exampleModalCenter" id="my-img" src="{{photo.photo.url}}" alt="" width="100%%" height="auto" style="cursor: pointer;">

    {% comment %} <h3 class="card-title"> {{ photo.photo }}</h3> {% endcomment %}
    <figcaption>
      <div class="icons">

        <a href="{% url 'photos:like' photo.pk %}">
            <!-- 사용자가 좋아요 누른 상태 -> 꽉찬 하트 -->
            <!--- python list in 사용 -->
            {% if request.user in photo.like_users.all%}
              <i class="fas fa-heart"></i>
            <!-- 안 누른 상태 -> 빈 하트-->
            {% else %}
              <i class="far fa-heart"></i>
            {% endif %}
        </a>
      </div>
    </figcaption>
  </figure>





<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">{{ photo.user }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row no-gutters">
            <div class="col-md-8">
              <img src="{{ photo.photo.url }}" class="card-img" alt="...">
            </div>
            <div class="col-md-4">
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        {% if photo.user == user %}
          <form action="{% url 'photos:delete' photo.pk  %}" method="POST" style="display: inline;">
            {% csrf_token %}
            <input type="submit" value="DELETE">
          </form>
        {% endif %}
        {% comment %} <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button> {% endcomment %}
      </div>
    </div>
  </div>
</div>

config/templates/photos/detail.html
{% extends 'base.html' %}
{% load make_link %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
{% include 'photos/_follow.html' %}

<h1 class="text-center">DETAIL</h1>

<p>글 번호:{{photo.pk}}</p>
<p>글 제목:{{photo.photo}}</p>
<p>사진 나와라~{{ photo.photo.url }}</p>
<img src="{{ photo.photo.url}}" alt="" width="200" height="200">
<p>글 내용:{{photo|hashtag_link|safe }}</p>
<p>생성시각:{{photo.created_at}}</p>
<p>수정시각:{{photo.updated_at}}</p>
<hr>

<a href="{% url 'photos:index' %}">[BACK]</a>
{% if request.user == photo.user %}
  <form action="{% url 'photos:delete' photo.pk %}" method="POST">
    {% csrf_token %}
    {% buttons submit='DELETE'%}
    {% endbuttons %}
  </form>
  <a href="{% url 'photos:update' photo.pk %}">[UPDATE]</a>
{% endif %}
<hr>

{% if user.is_authenticated %}
<form action="{% url 'photos:comment_create' photo.pk %}" method="POST" style="display:inline;"> 
  {% csrf_token %}
  {{ comment_form }}
  {% buttons submit='댓글 작성'%}
  {% endbuttons %}
</form>
{% else %}
<a href="{% url 'accounts:login' %}">[댓글 작성하려면 로그인 해주세요.]</a>
{% endif %}

<hr>
<p><b>댓글목록({{ comments|length }}개)</b></p>
{% for comment in comments %}
  <li>
    <p>[{{ forloop.revcounter }}] {{comment.content}}
    {% if comment.user == request.user %}
      <form action="{% url 'photos:comment_delete' photo.pk comment.pk %}" method="POST" style="display:inline;">
        {% csrf_token %}
        {% buttons submit='삭제'%}
        {% endbuttons %}
      </from>
    {% endif %}
  </li>
{% empty %}
  <p>댓글이 없는데요..ㅠㅠㅜ</p>
{% endfor %}

{% endblock %}

config/templates/photos/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
{% if request.resolver_match.url_name == 'create' %}
  <h1>CREATE</h1>
{% else %}
  <h1>UPDATE<h1>
{% endif %}
<hr>
<div class ="container">
  <form action="" method='POST' enctype="multipart/form-data" class="mx-auto" style="max-width: 500px;">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    <div>
      {% buttons submit='제출' reset='초기화' %}
      {% endbuttons %}
    </div>
  </form>  
</div> 
<!-- action 갑이 공백일 경우, 현재 위치하고 있는 주소로 요청을 보낸다.
폼을 던져주는 경로, DB에 저장하는 경로가 동일하다면 공백으로 처리해도 상관없다.-->

<hr>
<div class="container">
  {% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'photos:index'  %}">[BACK]</a>
  {% else %}
    <a href="{% url 'photos:detail' photo.pk %}">[BACK]</a>
  {% endif %}
</div>


{% endblock body %}

config/templates/photos/hashtag.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ hashtag.content }} 게시글 모아보기</h1>
<h4>{{ photos|length }} 개의 글이 있습니다.</h4>
<hr>
{% for photo in photos %}
  <p>글 제목:{{ photo.photo }}</p>
  <p>글 내용: {{ photo.content }}</p>
  <p>{{ photo.comment_set.all|length }}개의 댓글이 있습니다.</p>
  <p>{{ photo.like_users.all|length }}명이 이글을 좋아합니다.</p>
  <a href="{% url 'photos:detail' photo.pk %}">게시글 바로가기</a>
{% endfor %}
{% endblock %}

config/templates/photos/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block css %}

  <!--<link rel="stylesheet" href="{% static 'stylesheets/hover.css'%}">-->
  <link rel="stylesheet" href="{% static 'stylesheets/mouseover.css'%}">
  <!--<link rel="stylesheet" href="{% static 'stylesheets/background.css'%}">-->

{% endblock css %}

{% block body %}


{% comment %} <h1 class='text-center'>Articles</h1> {% endcomment %}

{% comment %} <a href="{% url 'photos:create' %}">[NEW]</a> {% endcomment %}
{% comment %} <hr> {% endcomment %}


{% comment %} <div class="progress" style="height: 1px;">
  <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
</div>
<div class="progress" style="height: 20px;">
  <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
</div> {% endcomment %}
</br>
<p class='text-center'>게시물     Like    근처</p> 

<div id="portfolio">
  {% for photo in photos %}
    
    {% include 'photos/_photo.html' %}
  {% endfor %}
  <hr>
</div>


<script>
  const image = document.getElementById('my-img')
  image.addEventListener('mouseover', function(){
    
    <h5 class="card-title">작성자 : {{ photo.user }}</h5>
    <h5 class="card-title">사진 : {{ photo.photo }}</h5>

  })

  /* Demo purposes only */
  $(".hover").mouseleave(
    function () {
      $(this).removeClass("hover");
    }
  );

  
</script>

{% endblock %}

config/templates/photos/photo_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<!-- URL Resolver를 사용해서 제목값 분기 -->
{% if request.resolver_match.url_name == 'list' %}
  <h1>List</h1>
{% else %}
  <h1>Explore</h1>
{% endif %}
<hr>
{% for photo in photos %}
  <p>글 제목: {{ photo.photo }}</p>
  <p>글 내용: {{ photo.content }}</p>
  <hr>
  <form action="{% url 'photos:comment_create' photo.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    {% buttons submit='댓글작성' %}
    {% endbuttons %}
  </form>
  <hr>
{% endfor %}
{% endblock %}

config/templates/photos/test.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'stylesheets/test.css' %}">
</head>
<body>

<div class="toolbar mb2 mt2">
  <button class="btn fil-cat" href="" data-rel="all">All</button>
  <button class="btn fil-cat" data-rel="web">Websites</button>
  <button class="btn fil-cat" data-rel="flyers">Flyers</button>
  <button class="btn fil-cat" data-rel="bcards">Business Cards</button>
</div> 

<div id="portfolio">
  <div class="tile scale-anm web all">
        <img src="http://demo.themerain.com/charm/wp-content/uploads/2015/04/2-mon_1092-300x234.jpg" alt="" />
  </div>
  <div class="tile scale-anm bcards all">
    <img src="http://demo.themerain.com/charm/wp-content/uploads/2015/04/jti-icons_08-300x172.jpg" alt="" />
  </div>
  <div class="tile scale-anm web all">
    <img src="http://demo.themerain.com/charm/wp-content/uploads/2015/04/emi_haze-300x201.jpg" alt="" />
  </div>
  <div class="tile scale-anm web all">
            <img src="http://demo.themerain.com/charm/wp-content/uploads/2015/04/codystretch-300x270.jpg" alt="" />
  </div>
  <div class="tile scale-anm flyers all">
        <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97190&w=350&h=190" alt="" />
  </div>
  <div class="tile scale-anm bcards all">
            <img src="https://placeholdit.imgix.net/~text?txtsize=19&txt=200%C3%97290&w=200&h=290" alt="" />
  </div>
  <div class="tile scale-anm flyers all">
    <img src="http://demo.themerain.com/charm/wp-content/uploads/2015/04/jti-icons_08-300x172.jpg" alt="" />
  </div>
  <div class="tile scale-anm flyers all">
    <img src="http://demo.themerain.com/charm/wp-content/uploads/2015/04/transmission_01-300x300.jpg" alt="" />
  </div>
  <div class="tile scale-anm web all">
        <img src="https://placeholdit.imgix.net/~text?txtsize=19&txt=200%C3%97290&w=200&h=290" alt="" />
  </div>
  <div class="tile scale-anm flyers all">
        <img src="https://placeholdit.imgix.net/~text?txtsize=19&txt=200%C3%97290&w=200&h=290" alt="" /> 
  </div>
  <div class="tile scale-anm web all">
        <img src="http://demo.themerain.com/charm/wp-content/uploads/2015/04/the-ninetys-brand_02-300x300.jpg" alt="" />
  </div>
  <div class="tile scale-anm bcards all">
            <img src="http://demo.themerain.com/charm/wp-content/uploads/2015/04/15-dia_1092-1-300x300.jpg" alt="" />
  </div>
  <div class="tile scale-anm web all">
            <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97190&w=350&h=190" alt="" /> 
  </div>
  <div class="tile scale-anm bcards all">
          <img src="http://demo.themerain.com/charm/wp-content/uploads/2015/04/emi_haze-300x201.jpg" alt="" />  
  </div>
  <div class="tile scale-anm web all">
            <img src="http://demo.themerain.com/charm/wp-content/uploads/2015/04/transmission_01-300x300.jpg" alt="" />
  </div> 
  <div class="tile scale-anm web all">
      <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97190&w=350&h=190" alt="" />  
  </div> 
  <div class="tile scale-anm bcards all">     
      <img src="https://unsplash.com/photos/jPQE61INdTgw=200&h=290" alt="" />
  </div>
</div>

<div style="clear:both;"></div>  


</body>
</html>