accounts/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup, name='signup'), 
    path('login/',views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<str:username>/', views.profile, name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('photos/', include('photos.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'photos'

urlpatterns = [
    path('',views.index, name='index'),    # READ - Index
    #path('new/',views.new, name='new'),     # CREATE - 폼 전달
    path('create/',views.create, name='create'),   # CREATE - DB 저장
    path('<int:photo_pk>/',views.detail, name='detail'),     # READ - Detail
    path('<int:photo_pk>/delete/', views.delete, name='delete'),     # delete
    path('<int:photo_pk>/update/', views.update, name='update'),     # UPDATE - DB 저장
    path('<int:photo_pk>/comment/', views.comment_create, name='comment_create'), # 댓글 생성
    path('<int:photo_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'), # 댓글 삭제
    path('<int:photo_pk>/like/', views.like, name='like'),
    path('<int:photo_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
    path('list/', views.list, name='list'),
    path('explore/', views.explore, name='explore'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
    path('test/', views.test, name='test'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
  followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='follwings')

photos/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
  content = models.TextField(unique=True)

  def __str__(self):
    return self.content

class Photo(models.Model):
  photo = models.ImageField()
  content = models.TextField()
  longitude = models.FloatField()
  latitude = models.FloatField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
  hashtags = models.ManyToManyField(Hashtag, blank=True)
  
  def __str__(self):
    return f'[{self.pk}] {self.photo}'

class Comment(models.Model):
  photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  content = models.TextField(max_length=300)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  class Meta:
    ordering = ['-pk',]

  def __str__(self):
    return self.content  

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class CustomUserChangeForm(UserChangeForm):

  class Meta:
    # User 클래스를 바로 사용하는 것이 아니라, get_user_model()을 사용해서 User 클래스를 참조한다.
    model = get_user_model()
    # UserChangeForm -> User 클래스 -> AbstractUser 클래스 상속
    # Django 공식 문서 : user-model
    fields = ('email', 'last_name', 'first_name')

class CustomUserCreationForm(UserCreationForm):
  class Meta:
    model = get_user_model()
    fields = ('username', 'password1', 'password2', 'email',)

accounts/views.py
from IPython import embed
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import CustomUserChangeForm, CustomUserCreationForm
# Create your views here.  

# Authentication(인증) -> 신원 확인
# - 자신이 누구라고 주장하는 사람의 신원을 확인하는 것

def signup(request):
  if request.user.is_authenticated:
    return redirect('photos:index')
  if request.method == 'POST':
    form = CustomUserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      auth_login(request, user)
      return redirect('photos:index')
  else:
    form = CustomUserCreationForm
  context = {'form':form}
  return render(request, 'accounts/auth_form.html', context)

def login(request):
  if request.user.is_authenticated:
    return redirect('photos:index')

  if request.method =='POST':
    form = AuthenticationForm(request, request.POST)
    # embed()
    if form.is_valid():
      auth_login(request, form.get_user())
      return redirect(request.GET.get('next') or 'photos:index')
  else:
    form = AuthenticationForm()
  context = {'form':form}
  return render(request, 'accounts/login.html', context)

def logout(request):
  auth_logout(request)
  # embed()
  return redirect('accounts:login')

@require_POST
def delete(request):
  request.user.delete()
  return redirect('photos:index')

# 회원 정보 수정
@login_required
def update(request):
  if request.method == 'POST':
    form = CustomUserChangeForm(request.POST, instance=request.user)
    if form.is_valid():
      form.save()
      return redirect('photos:index')
  else:
    form = CustomUserChangeForm(instance=request.user)
  context={'form':form}
  return render(request, 'accounts/auth_form.html', context)

# 비밀번호 변경
@login_required
def change_password(request):
  if request.method == 'POST':
    form = PasswordChangeForm(request.user, request.POST)
    if form.is_valid():
      user = form.save()
      update_session_auth_hash(request, user)
      return redirect('photos:index')
  else:
    form = PasswordChangeForm(request.user)
  context = {'form': form}
  return render(request, 'accounts/auth_form.html', context)

def profile(request, username):
  person = get_object_or_404(get_user_model(), username=username)
  context = {'person':person,}
  return render(request, 'accounts/profile.html', context)

config/templates/accounts/auth_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'signup' %}
  <h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
  <h1>로그인</h1>
{% elif request.resolver_match.url_name == 'update' %}
  <h1>회원정보 수정</h1>
{% else %}
  <h1>비밀번호 변경</h1>
{% endif %}

<hr>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form layout='inline' %}
  {% buttons submit='가입' reset='초기화' %}
  {% endbuttons %}
</form>
{% endblock %}

config/templates/accounts/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'signup' %}
  <h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
  <h1>로그인</h1>
{% elif request.resolver_match.url_name == 'update' %}
  <h1>회원정보 수정</h1>
{% else %}
  <h1>비밀번호 변경</h1>
{% endif %}

<hr>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form layout='inline' %}
  {% buttons submit='로그인' reset='초기화' %}
  {% endbuttons %}
  <a href="{% provider_login_url 'kakao'%}" class="btn btn-warning">카카오 로그인</a>
</form>
{% endblock %}

config/templates/accounts/profile.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ person.username }}님의 Profile</h1>
<hr>
<h3>{{ person.username }}님이 작성한 게시글</h3>
<div class="row">
  {% for photo in person.photo_set.all %}
    <div class="col-12 col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">
          글 제목 : {{ photo.title }}
          </h5>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
<br>
<h3>{{ person.username }}님이 작성한 댓글</h3>
<div class="row">
  {% for comment in person.comment_set.all %}
    <div class="col-12 col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ comments.content }}</h5>
          <p class="card-text">작성 시각 : {{ comment.created_at|date:"SHORT_DATETIME_FORMAT" }}</p>
          <a href="{% url 'photos:detail' comment.photo.pk %}" class="btn btn-primary">게시글 확인</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}